services:
  app:
    env_file:
      - .env
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    image: app
    restart: unless-stopped
    build:
      context: .
      dockerfile: App/Dockerfile
    depends_on:
      - postgres

  postgres:
    image: postgres:18.1-alpine3.22
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: