// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524190328_FixForeignKeyForMemberTags")]
    partial class FixForeignKeyForMemberTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Application.AnalyticsDTOs.ClanWarPlayerSummaryDto", b =>
                {
                    b.Property<string>("Tag")
                        .HasColumnType("text");

                    b.Property<float>("AttackParticipationRate")
                        .HasColumnType("real");

                    b.Property<float>("AvarageMapPosition")
                        .HasColumnType("real");

                    b.Property<float>("AvarageOpponentMapPosition")
                        .HasColumnType("real");

                    b.Property<float>("AverageDestructionPercentage")
                        .HasColumnType("real");

                    b.Property<float>("AverageOpponentTownHallLevel")
                        .HasColumnType("real");

                    b.Property<float>("AverageStarsPerWar")
                        .HasColumnType("real");

                    b.Property<float>("AverageThMismatches")
                        .HasColumnType("real");

                    b.Property<float>("AverageTownHallLevel")
                        .HasColumnType("real");

                    b.Property<float>("FirstAttackParticipationRate")
                        .HasColumnType("real");

                    b.Property<float>("MirrorAttacksRate")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<short[]>("RecentWarsAttacks")
                        .IsRequired()
                        .HasColumnType("smallint[]");

                    b.Property<float>("SecondAttackParticipationRate")
                        .HasColumnType("real");

                    b.Property<float>("ThreeStarRateAgainstSameTh")
                        .HasColumnType("real");

                    b.HasKey("Tag");

                    b.ToTable((string)null);

                    b.ToView("mv_clan_war_player_summaries", (string)null);
                });

            modelBuilder.Entity("Application.AnalyticsDTOs.ClanWarSummaryDto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    b.Property<float>("AverageOpponentTownHall")
                        .HasColumnType("real")
                        .HasColumnName("AverageOpponentTownHall");

                    b.Property<float>("AverageOurTownHall")
                        .HasColumnType("real")
                        .HasColumnName("AverageOurTownHall");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EndTime");

                    b.Property<short>("ExpEarned")
                        .HasColumnType("smallint")
                        .HasColumnName("ExpEarned");

                    b.Property<short>("OpponentAttacks")
                        .HasColumnType("smallint")
                        .HasColumnName("OpponentAttacks");

                    b.Property<short>("OpponentClanLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("OpponentClanLevel");

                    b.Property<string>("OpponentClanName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("OpponentClanName");

                    b.Property<float>("OpponentDestructionPercentage")
                        .HasColumnType("real")
                        .HasColumnName("OpponentDestructionPercentage");

                    b.Property<short>("OpponentStars")
                        .HasColumnType("smallint")
                        .HasColumnName("OpponentStars");

                    b.Property<short>("OurAttacks")
                        .HasColumnType("smallint")
                        .HasColumnName("OurAttacks");

                    b.Property<float>("OurDestructionPercentage")
                        .HasColumnType("real")
                        .HasColumnName("OurDestructionPercentage");

                    b.Property<short>("OurStars")
                        .HasColumnType("smallint")
                        .HasColumnName("OurStars");

                    b.Property<short>("OurThreeStarsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("OurThreeStarsCount");

                    b.Property<float>("ParticipationRate")
                        .HasColumnType("real")
                        .HasColumnName("ParticipationRate");

                    b.Property<float>("StarsPerAttack")
                        .HasColumnType("real")
                        .HasColumnName("StarsPerAttack");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartTime");

                    b.Property<short>("TeamSize")
                        .HasColumnType("smallint")
                        .HasColumnName("TeamSize");

                    b.Property<float>("TownHallAdvantage")
                        .HasColumnType("real")
                        .HasColumnName("TownHallAdvantage");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("mv_clan_war_summaries", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Clans.ClanMember", b =>
                {
                    b.Property<string>("Tag")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .UseCollation("C");

                    b.Property<short>("BestBuilderBaseTrophies")
                        .HasColumnType("smallint");

                    b.Property<short>("BuilderBaseTrophies")
                        .HasColumnType("smallint");

                    b.Property<short>("BuilderHallLevel")
                        .HasColumnType("smallint");

                    b.Property<int>("ClanCapitalContributions")
                        .HasColumnType("integer");

                    b.Property<short>("ExpLevel")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsNowInClan")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<short>("TownHallLevel")
                        .HasColumnType("smallint");

                    b.Property<short>("Trophies")
                        .HasColumnType("smallint");

                    b.Property<string>("WarPreference")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<int>("WarStars")
                        .HasColumnType("integer");

                    b.HasKey("Tag");

                    b.ToTable("clan_members", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Clans.ClanWar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<short?>("ExpEarned")
                        .HasColumnType("smallint");

                    b.Property<short>("OpponentAttacks")
                        .HasColumnType("smallint");

                    b.Property<short>("OpponentClanLevel")
                        .HasColumnType("smallint");

                    b.Property<string>("OpponentClanName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OpponentClanTag")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .UseCollation("C");

                    b.Property<float>("OpponentDestructionPercentage")
                        .HasColumnType("real");

                    b.Property<short>("OpponentStars")
                        .HasColumnType("smallint");

                    b.Property<short>("OurAttacks")
                        .HasColumnType("smallint");

                    b.Property<float>("OurDestructionPercentage")
                        .HasColumnType("real");

                    b.Property<short>("OurStars")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<short>("TeamSize")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("OpponentClanTag");

                    b.HasIndex("StartTime", "EndTime");

                    b.ToTable("clan_wars", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Clans.ClanWarPlayerPerformance", b =>
                {
                    b.Property<int>("WarId")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerTag")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .UseCollation("C");

                    b.Property<short?>("Attack1Destruction")
                        .HasColumnType("smallint");

                    b.Property<short?>("Attack1Duration")
                        .HasColumnType("smallint");

                    b.Property<short?>("Attack1Stars")
                        .HasColumnType("smallint");

                    b.Property<short?>("Attack2Destruction")
                        .HasColumnType("smallint");

                    b.Property<short?>("Attack2Duration")
                        .HasColumnType("smallint");

                    b.Property<short?>("Attack2Stars")
                        .HasColumnType("smallint");

                    b.Property<string>("Defender1Tag")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .UseCollation("C");

                    b.Property<string>("Defender2Tag")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .UseCollation("C");

                    b.Property<short>("MapPosition")
                        .HasColumnType("smallint");

                    b.Property<short?>("Opponent1Position")
                        .HasColumnType("smallint");

                    b.Property<short?>("Opponent1TownHallLevel")
                        .HasColumnType("smallint");

                    b.Property<short?>("Opponent2Position")
                        .HasColumnType("smallint");

                    b.Property<short?>("Opponent2TownHallLevel")
                        .HasColumnType("smallint");

                    b.Property<short>("TownHallLevel")
                        .HasColumnType("smallint");

                    b.HasKey("WarId", "PlayerTag");

                    b.HasIndex("PlayerTag");

                    b.ToTable("clan_war_player_performances", (string)null);
                });

            modelBuilder.Entity("Domain.Models.SeasonStats", b =>
                {
                    b.Property<DateOnly>("SeasonDate")
                        .HasColumnType("date");

                    b.Property<string>("PlayerTag")
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Donations")
                        .HasColumnType("integer");

                    b.Property<int>("DonationsReceived")
                        .HasColumnType("integer");

                    b.HasKey("SeasonDate", "PlayerTag");

                    b.HasIndex("PlayerTag");

                    b.ToTable("season_stats", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Clans.ClanWarPlayerPerformance", b =>
                {
                    b.HasOne("Domain.Models.Clans.ClanMember", "Member")
                        .WithMany("ClanWarPerformances")
                        .HasForeignKey("PlayerTag")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Models.Clans.ClanWar", "War")
                        .WithMany("PlayersPerformances")
                        .HasForeignKey("WarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("War");
                });

            modelBuilder.Entity("Domain.Models.SeasonStats", b =>
                {
                    b.HasOne("Domain.Models.Clans.ClanMember", "Player")
                        .WithMany("SeasonStats")
                        .HasForeignKey("PlayerTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Domain.Models.Clans.ClanMember", b =>
                {
                    b.Navigation("ClanWarPerformances");

                    b.Navigation("SeasonStats");
                });

            modelBuilder.Entity("Domain.Models.Clans.ClanWar", b =>
                {
                    b.Navigation("PlayersPerformances");
                });
#pragma warning restore 612, 618
        }
    }
}
