// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Analytics.ClanWarLeagues.ClanWarLeagueGroupSummary", b =>
                {
                    b.Property<string>("Season")
                        .HasColumnType("text");

                    b.Property<float>("AverageOpponentTownHall")
                        .HasColumnType("real");

                    b.Property<float>("AverageOurDestructionPercentage")
                        .HasColumnType("real");

                    b.Property<float>("AverageOurTownHall")
                        .HasColumnType("real");

                    b.Property<float>("AverageStarsPerAttack")
                        .HasColumnType("real");

                    b.Property<float>("ParticipationRate")
                        .HasColumnType("real");

                    b.Property<short?>("Place")
                        .HasColumnType("smallint");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("TeamSize")
                        .HasColumnType("smallint");

                    b.Property<short>("TotalLosses")
                        .HasColumnType("smallint");

                    b.Property<short>("TotalOpponentAttacks")
                        .HasColumnType("smallint");

                    b.Property<short>("TotalOpponentStars")
                        .HasColumnType("smallint");

                    b.Property<short>("TotalOurAttacks")
                        .HasColumnType("smallint");

                    b.Property<short>("TotalOurStars")
                        .HasColumnType("smallint");

                    b.Property<short>("TotalOurThreeStars")
                        .HasColumnType("smallint");

                    b.Property<short>("TotalWins")
                        .HasColumnType("smallint");

                    b.Property<float>("TownHallAdvantage")
                        .HasColumnType("real");

                    b.HasKey("Season");

                    b.ToTable((string)null);

                    b.ToView("mv_clan_war_league_group_summaries", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Analytics.ClanWarLeagues.ClanWarLeaguesPlayerSummary", b =>
                {
                    b.Property<string>("Tag")
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Season")
                        .HasColumnType("text");

                    b.Property<float>("AttackParticipationRate")
                        .HasColumnType("real");

                    b.Property<float>("AverageDestructionPercentage")
                        .HasColumnType("real");

                    b.Property<float>("AverageMapPosition")
                        .HasColumnType("real");

                    b.Property<float>("AverageOpponentMapPosition")
                        .HasColumnType("real");

                    b.Property<float>("AverageOpponentTownHallLevel")
                        .HasColumnType("real");

                    b.Property<float>("AverageStarsPerAttack")
                        .HasColumnType("real");

                    b.Property<float>("AverageThMismatches")
                        .HasColumnType("real");

                    b.Property<float>("AverageTownHallLevel")
                        .HasColumnType("real");

                    b.PrimitiveCollection<short[]>("CwlRoundsAttacks")
                        .IsRequired()
                        .HasColumnType("smallint[]")
                        .HasColumnName("RecentCwlRoundsAttacks");

                    b.Property<float>("MirrorAttacksRate")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("ThreeStarRateAgainstSameTh")
                        .HasColumnType("real");

                    b.Property<int>("TotalRoundsOnMap")
                        .HasColumnType("integer");

                    b.HasKey("Tag", "Season");

                    b.ToTable((string)null);

                    b.ToView("mv_clan_war_leagues_player_summaries", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Analytics.ClanWars.ClanWarPlayerSummary", b =>
                {
                    b.Property<string>("Tag")
                        .HasColumnType("character varying(10)");

                    b.Property<float>("AttackParticipationRate")
                        .HasColumnType("real");

                    b.Property<float>("AverageDestructionPercentage")
                        .HasColumnType("real");

                    b.Property<float>("AverageMapPosition")
                        .HasColumnType("real");

                    b.Property<float>("AverageOpponentMapPosition")
                        .HasColumnType("real");

                    b.Property<float>("AverageOpponentTownHallLevel")
                        .HasColumnType("real");

                    b.Property<float>("AverageStarsPerAttack")
                        .HasColumnType("real");

                    b.Property<float>("AverageStarsPerWar")
                        .HasColumnType("real");

                    b.Property<float>("AverageThMismatches")
                        .HasColumnType("real");

                    b.Property<float>("AverageTownHallLevel")
                        .HasColumnType("real");

                    b.Property<float>("FirstAttackParticipationRate")
                        .HasColumnType("real");

                    b.Property<float>("MirrorAttacksRate")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<short[]>("RecentWarsAttacks")
                        .IsRequired()
                        .HasColumnType("smallint[]");

                    b.Property<float>("SecondAttackParticipationRate")
                        .HasColumnType("real");

                    b.Property<float>("ThreeStarRateAgainstSameTh")
                        .HasColumnType("real");

                    b.HasKey("Tag");

                    b.ToTable((string)null);

                    b.ToView("mv_clan_war_player_summaries", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Analytics.ClanWars.ClanWarSummary", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<float>("AverageOpponentTownHall")
                        .HasColumnType("real");

                    b.Property<float>("AverageOurTownHall")
                        .HasColumnType("real");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("ExpEarned")
                        .HasColumnType("smallint");

                    b.Property<short>("OpponentAttacks")
                        .HasColumnType("smallint");

                    b.Property<short>("OpponentClanLevel")
                        .HasColumnType("smallint");

                    b.Property<string>("OpponentClanName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("OpponentDestructionPercentage")
                        .HasColumnType("real");

                    b.Property<short>("OpponentStars")
                        .HasColumnType("smallint");

                    b.Property<short>("OurAttacks")
                        .HasColumnType("smallint");

                    b.Property<float>("OurDestructionPercentage")
                        .HasColumnType("real");

                    b.Property<short>("OurStars")
                        .HasColumnType("smallint");

                    b.Property<short>("OurThreeStarsCount")
                        .HasColumnType("smallint");

                    b.Property<float>("ParticipationRate")
                        .HasColumnType("real");

                    b.Property<float>("StarsPerAttack")
                        .HasColumnType("real");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("TeamSize")
                        .HasColumnType("smallint");

                    b.Property<float>("TownHallAdvantage")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("mv_clan_war_summaries", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ClanMember", b =>
                {
                    b.Property<string>("Tag")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .UseCollation("C");

                    b.Property<int?>("ActivityStateMemberInternalId")
                        .HasColumnType("integer");

                    b.Property<short>("BestBuilderBaseTrophies")
                        .HasColumnType("smallint");

                    b.Property<short>("BuilderBaseTrophies")
                        .HasColumnType("smallint");

                    b.Property<short>("BuilderHallLevel")
                        .HasColumnType("smallint");

                    b.Property<int>("ClanCapitalContributions")
                        .HasColumnType("integer");

                    b.Property<short>("ExpLevel")
                        .HasColumnType("smallint");

                    b.Property<int>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InternalId"));

                    b.Property<bool>("IsNowInClan")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<short>("TownHallLevel")
                        .HasColumnType("smallint");

                    b.Property<short>("Trophies")
                        .HasColumnType("smallint");

                    b.Property<string>("WarPreference")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<int>("WarStars")
                        .HasColumnType("integer");

                    b.HasKey("Tag");

                    b.HasIndex("ActivityStateMemberInternalId");

                    b.ToTable("clan_members", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ClanWarLeagues.ClanWarLeagueGroup", b =>
                {
                    b.Property<string>("Season")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<short?>("Place")
                        .HasColumnType("smallint");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<short>("TeamSize")
                        .HasColumnType("smallint");

                    b.HasKey("Season");

                    b.ToTable("clan_war_league_groups", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ClanWarLeagues.ClanWarLeaguePlayerPerformance", b =>
                {
                    b.Property<string>("WarTag")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<string>("PlayerTag")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .UseCollation("C");

                    b.Property<short?>("AttackDestruction")
                        .HasColumnType("smallint");

                    b.Property<short?>("AttackDuration")
                        .HasColumnType("smallint");

                    b.Property<short?>("AttackStars")
                        .HasColumnType("smallint");

                    b.Property<string>("DefenderTag")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .UseCollation("C");

                    b.Property<short>("MapPosition")
                        .HasColumnType("smallint");

                    b.Property<short?>("OpponentPosition")
                        .HasColumnType("smallint");

                    b.Property<short?>("OpponentTownHallLevel")
                        .HasColumnType("smallint");

                    b.Property<short>("TownHallLevel")
                        .HasColumnType("smallint");

                    b.HasKey("WarTag", "PlayerTag");

                    b.HasIndex("PlayerTag");

                    b.ToTable("clan_war_league_player_performances", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ClanWarLeagues.ClanWarLeagueWar", b =>
                {
                    b.Property<string>("WarTag")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<short>("OpponentAttacks")
                        .HasColumnType("smallint");

                    b.Property<short>("OpponentClanLevel")
                        .HasColumnType("smallint");

                    b.Property<string>("OpponentClanName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OpponentClanTag")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .UseCollation("C");

                    b.Property<float>("OpponentDestructionPercentage")
                        .HasColumnType("real");

                    b.Property<short>("OpponentStars")
                        .HasColumnType("smallint");

                    b.Property<short>("OurAttacks")
                        .HasColumnType("smallint");

                    b.Property<float>("OurDestructionPercentage")
                        .HasColumnType("real");

                    b.Property<short>("OurStars")
                        .HasColumnType("smallint");

                    b.Property<short>("Round")
                        .HasColumnType("smallint");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<DateTime>("WarStartTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("WarTag");

                    b.HasIndex("Season");

                    b.ToTable("clan_war_league_wars", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ClanWars.ClanWar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<short?>("ExpEarned")
                        .HasColumnType("smallint");

                    b.Property<short>("OpponentAttacks")
                        .HasColumnType("smallint");

                    b.Property<short>("OpponentClanLevel")
                        .HasColumnType("smallint");

                    b.Property<string>("OpponentClanName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OpponentClanTag")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .UseCollation("C");

                    b.Property<float>("OpponentDestructionPercentage")
                        .HasColumnType("real");

                    b.Property<short>("OpponentStars")
                        .HasColumnType("smallint");

                    b.Property<short>("OurAttacks")
                        .HasColumnType("smallint");

                    b.Property<float>("OurDestructionPercentage")
                        .HasColumnType("real");

                    b.Property<short>("OurStars")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<short>("TeamSize")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("OpponentClanTag", "StartTime");

                    b.ToTable("clan_wars", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ClanWars.ClanWarPlayerPerformance", b =>
                {
                    b.Property<int>("WarId")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerTag")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .UseCollation("C");

                    b.Property<short?>("Attack1Destruction")
                        .HasColumnType("smallint");

                    b.Property<short?>("Attack1Duration")
                        .HasColumnType("smallint");

                    b.Property<short?>("Attack1Stars")
                        .HasColumnType("smallint");

                    b.Property<short?>("Attack2Destruction")
                        .HasColumnType("smallint");

                    b.Property<short?>("Attack2Duration")
                        .HasColumnType("smallint");

                    b.Property<short?>("Attack2Stars")
                        .HasColumnType("smallint");

                    b.Property<string>("Defender1Tag")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .UseCollation("C");

                    b.Property<string>("Defender2Tag")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .UseCollation("C");

                    b.Property<short>("MapPosition")
                        .HasColumnType("smallint");

                    b.Property<short?>("Opponent1Position")
                        .HasColumnType("smallint");

                    b.Property<short?>("Opponent1TownHallLevel")
                        .HasColumnType("smallint");

                    b.Property<short?>("Opponent2Position")
                        .HasColumnType("smallint");

                    b.Property<short?>("Opponent2TownHallLevel")
                        .HasColumnType("smallint");

                    b.Property<short>("TownHallLevel")
                        .HasColumnType("smallint");

                    b.HasKey("WarId", "PlayerTag");

                    b.HasIndex("PlayerTag");

                    b.ToTable("clan_war_player_performances", (string)null);
                });

            modelBuilder.Entity("Domain.Models.PlayerActivitySnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("MemberInternalId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SnapshotTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MemberInternalId", "Id")
                        .IsDescending(false, true);

                    b.ToTable("player_activity_snapshots", (string)null);
                });

            modelBuilder.Entity("Domain.Models.PlayerActivityState", b =>
                {
                    b.Property<int>("MemberInternalId")
                        .HasColumnType("integer");

                    b.Property<long>("ActivityScore")
                        .HasColumnType("bigint");

                    b.HasKey("MemberInternalId");

                    b.ToTable("player_activity_states", (string)null);
                });

            modelBuilder.Entity("Domain.Models.SeasonStats", b =>
            modelBuilder.Entity("Domain.Models.Statistics.PlayerSeasonStats", b =>
                {
                    b.Property<DateOnly>("SeasonDate")
                        .HasColumnType("date");

                    b.Property<string>("PlayerTag")
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Donations")
                        .HasColumnType("integer");

                    b.Property<int>("DonationsReceived")
                        .HasColumnType("integer");

                    b.HasKey("SeasonDate", "PlayerTag");

                    b.HasIndex("PlayerTag");

                    b.ToTable("season_stats", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Analytics.ClanWarLeagues.ClanWarLeaguesPlayerSummary", b =>
                {
                    b.HasOne("Domain.Models.ClanMember", "ClanMember")
                        .WithMany("ClanWarLeaguesPlayerSummaries")
                        .HasForeignKey("Tag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClanMember");
                });

            modelBuilder.Entity("Domain.Models.Analytics.ClanWars.ClanWarPlayerSummary", b =>
                {
                    b.HasOne("Domain.Models.ClanMember", "ClanMember")
                        .WithOne("ClanWarPlayerSummary")
                        .HasForeignKey("Domain.Models.Analytics.ClanWars.ClanWarPlayerSummary", "Tag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClanMember");
                });

            modelBuilder.Entity("Domain.Models.ClanMember", b =>
                {
                    b.HasOne("Domain.Models.PlayerActivityState", "ActivityState")
                        .WithMany()
                        .HasForeignKey("ActivityStateMemberInternalId");

                    b.Navigation("ActivityState");
                });

            modelBuilder.Entity("Domain.Models.ClanWarLeagues.ClanWarLeaguePlayerPerformance", b =>
                {
                    b.HasOne("Domain.Models.ClanMember", "Member")
                        .WithMany("ClanWarLeaguePerformances")
                        .HasForeignKey("PlayerTag")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Models.ClanWarLeagues.ClanWarLeagueWar", "LeagueWar")
                        .WithMany("PlayerPerformances")
                        .HasForeignKey("WarTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeagueWar");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Domain.Models.ClanWarLeagues.ClanWarLeagueWar", b =>
                {
                    b.HasOne("Domain.Models.ClanWarLeagues.ClanWarLeagueGroup", "Group")
                        .WithMany("Wars")
                        .HasForeignKey("Season")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Domain.Models.ClanWars.ClanWarPlayerPerformance", b =>
                {
                    b.HasOne("Domain.Models.ClanMember", "Member")
                        .WithMany("ClanWarPerformances")
                        .HasForeignKey("PlayerTag")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Models.ClanWars.ClanWar", "War")
                        .WithMany("PlayersPerformances")
                        .HasForeignKey("WarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("War");
                });

            modelBuilder.Entity("Domain.Models.PlayerActivitySnapshot", b =>
                {
                    b.HasOne("Domain.Models.ClanMember", "Member")
                        .WithMany("ActivitySnapshots")
                        .HasForeignKey("MemberInternalId")
                        .HasPrincipalKey("InternalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Domain.Models.PlayerActivityState", b =>
                {
                    b.HasOne("Domain.Models.ClanMember", "Member")
                        .WithOne()
                        .HasForeignKey("Domain.Models.PlayerActivityState", "MemberInternalId")
                        .HasPrincipalKey("Domain.Models.ClanMember", "InternalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Domain.Models.Statistics.PlayerSeasonStats", b =>
                {
                    b.HasOne("Domain.Models.ClanMember", "Player")
                        .WithMany("SeasonStats")
                        .HasForeignKey("PlayerTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Domain.Models.ClanMember", b =>
                {
                    b.Navigation("ActivitySnapshots");

                    b.Navigation("ClanWarLeaguePerformances");

                    b.Navigation("ClanWarLeaguesPlayerSummaries");

                    b.Navigation("ClanWarPerformances");

                    b.Navigation("ClanWarPlayerSummary");

                    b.Navigation("SeasonStats");
                });

            modelBuilder.Entity("Domain.Models.ClanWarLeagues.ClanWarLeagueGroup", b =>
                {
                    b.Navigation("Wars");
                });

            modelBuilder.Entity("Domain.Models.ClanWarLeagues.ClanWarLeagueWar", b =>
                {
                    b.Navigation("PlayerPerformances");
                });

            modelBuilder.Entity("Domain.Models.ClanWars.ClanWar", b =>
                {
                    b.Navigation("PlayersPerformances");
                });
#pragma warning restore 612, 618
        }
    }
}
